"""Romaji composition helpers shared by touch-flick preview and dispatch."""
from __future__ import annotations

from typing import Any

TOUCH_FLICK_WINDOWS_IME_PROFILE = "windows11_microsoft_ime"
TOUCH_FLICK_COMPOSITION_MODE = "romaji_us_ime"

ROMAJI_US_IME_KEYCODES: dict[str, tuple[str, ...]] = {
    "3042": ("KC_A",),
    "3041": ("KC_L", "KC_A"),
    "3044": ("KC_I",),
    "3043": ("KC_L", "KC_I"),
    "3046": ("KC_U",),
    "3045": ("KC_L", "KC_U"),
    "3048": ("KC_E",),
    "3047": ("KC_L", "KC_E"),
    "304A": ("KC_O",),
    "3049": ("KC_L", "KC_O"),
    "304B": ("KC_K", "KC_A"),
    "304D": ("KC_K", "KC_I"),
    "304F": ("KC_K", "KC_U"),
    "3051": ("KC_K", "KC_E"),
    "3053": ("KC_K", "KC_O"),
    "304C": ("KC_G", "KC_A"),
    "304E": ("KC_G", "KC_I"),
    "3050": ("KC_G", "KC_U"),
    "3052": ("KC_G", "KC_E"),
    "3054": ("KC_G", "KC_O"),
    "3055": ("KC_S", "KC_A"),
    "3057": ("KC_S", "KC_I"),
    "3059": ("KC_S", "KC_U"),
    "305B": ("KC_S", "KC_E"),
    "305D": ("KC_S", "KC_O"),
    "3056": ("KC_Z", "KC_A"),
    "3058": ("KC_Z", "KC_I"),
    "305A": ("KC_Z", "KC_U"),
    "305C": ("KC_Z", "KC_E"),
    "305E": ("KC_Z", "KC_O"),
    "305F": ("KC_T", "KC_A"),
    "3061": ("KC_T", "KC_I"),
    "3064": ("KC_T", "KC_U"),
    "3066": ("KC_T", "KC_E"),
    "3068": ("KC_T", "KC_O"),
    "3060": ("KC_D", "KC_A"),
    "3062": ("KC_D", "KC_I"),
    "3065": ("KC_D", "KC_U"),
    "3067": ("KC_D", "KC_E"),
    "3069": ("KC_D", "KC_O"),
    "3063": ("KC_L", "KC_T", "KC_U"),
    "306A": ("KC_N", "KC_A"),
    "306B": ("KC_N", "KC_I"),
    "306C": ("KC_N", "KC_U"),
    "306D": ("KC_N", "KC_E"),
    "306E": ("KC_N", "KC_O"),
    "306F": ("KC_H", "KC_A"),
    "3072": ("KC_H", "KC_I"),
    "3075": ("KC_H", "KC_U"),
    "3078": ("KC_H", "KC_E"),
    "307B": ("KC_H", "KC_O"),
    "3070": ("KC_B", "KC_A"),
    "3073": ("KC_B", "KC_I"),
    "3076": ("KC_B", "KC_U"),
    "3079": ("KC_B", "KC_E"),
    "307C": ("KC_B", "KC_O"),
    "3071": ("KC_P", "KC_A"),
    "3074": ("KC_P", "KC_I"),
    "3077": ("KC_P", "KC_U"),
    "307A": ("KC_P", "KC_E"),
    "307D": ("KC_P", "KC_O"),
    "307E": ("KC_M", "KC_A"),
    "307F": ("KC_M", "KC_I"),
    "3080": ("KC_M", "KC_U"),
    "3081": ("KC_M", "KC_E"),
    "3082": ("KC_M", "KC_O"),
    "3084": ("KC_Y", "KC_A"),
    "3083": ("KC_L", "KC_Y", "KC_A"),
    "3086": ("KC_Y", "KC_U"),
    "3085": ("KC_L", "KC_Y", "KC_U"),
    "3088": ("KC_Y", "KC_O"),
    "3087": ("KC_L", "KC_Y", "KC_O"),
    "3089": ("KC_R", "KC_A"),
    "308A": ("KC_R", "KC_I"),
    "308B": ("KC_R", "KC_U"),
    "308C": ("KC_R", "KC_E"),
    "308D": ("KC_R", "KC_O"),
    "308F": ("KC_W", "KC_A"),
    "3092": ("KC_W", "KC_O"),
    "3093": ("KC_N", "KC_N"),
    "3001": ("KC_COMM",),
    "3002": ("KC_DOT",),
    "30FC": ("KC_MINS",),
    "002E": ("KC_DOT",),
    "FF10": ("KC_0",),
    "FF11": ("KC_1",),
    "FF12": ("KC_2",),
    "FF13": ("KC_3",),
    "FF14": ("KC_4",),
    "FF15": ("KC_5",),
    "FF16": ("KC_6",),
    "FF17": ("KC_7",),
    "FF18": ("KC_8",),
    "FF19": ("KC_9",),
    "FF01": ("KC_EXLM",),
    "FF03": ("KC_HASH",),
    "FF04": ("KC_DLR",),
    "FF05": ("KC_PERC",),
    "FF08": ("KC_LPRN",),
    "FF09": ("KC_RPRN",),
    "FF0A": ("KC_ASTR",),
    "FF0B": ("KC_PLUS",),
    "FF0C": ("KC_COMM",),
    "FF0E": ("KC_DOT",),
    "FF0F": ("KC_SLSH",),
    "FF1A": ("KC_COLN",),
    "FF1C": ("KC_LT",),
    "FF1D": ("KC_EQL",),
    "FF1E": ("KC_GT",),
    "FF1F": ("KC_QUES",),
    "FF3B": ("KC_LBRC",),
    "FF3D": ("KC_RBRC",),
    "FF3E": ("KC_CIRC",),
    "FF5C": ("KC_PIPE",),
    "FF5E": ("KC_TILD",),
}

COMPOSITION_BLOCKING_REASON_BY_CODEPOINT: dict[str, str] = {
    "300C": "composition_policy_jis_kana_dependent",
    "300D": "composition_policy_jis_kana_dependent",
    "309B": "composition_policy_ime_specific_mark",
    "309C": "composition_policy_ime_specific_mark",
    "30FB": "composition_policy_ime_specific_mark",
    "3005": "composition_policy_ime_specific_mark",
    "3006": "composition_policy_ime_specific_mark",
    "30FD": "composition_policy_ime_specific_mark",
    "266A": "composition_policy_non_ascii_symbol",
    "2192": "composition_policy_non_ascii_symbol",
    "2606": "composition_policy_non_ascii_symbol",
    "20AC": "composition_policy_non_ascii_symbol",
    "FFE5": "composition_policy_non_ascii_symbol",
    "00B0": "composition_policy_non_ascii_symbol",
    "00D7": "composition_policy_non_ascii_symbol",
    "00F7": "composition_policy_non_ascii_symbol",
    "3013": "composition_policy_non_ascii_symbol",
    "2010": "composition_policy_non_ascii_symbol",
}

COMPOSITION_BLOCKING_REASON_POLICY: dict[str, list[str]] = {
    "composition_mode_requires_unicode_action": [
        "named_text_and_send_string_actions_use_text_send_preflight",
    ],
    "composition_policy_ime_specific_mark": [
        "dakuten_handakuten_mark_codepoints",
        "iteration_marks",
        "middle_dot",
    ],
    "composition_policy_jis_kana_dependent": [
        "corner_brackets",
    ],
    "composition_policy_non_ascii_symbol": [
        "currency",
        "math_symbols",
        "arrows",
        "music_symbols",
        "placeholder_marks",
        "emoji",
        "katakana_without_romaji_policy",
    ],
}

COMPOSITION_BLOCKED_OUTPUTS = (
    "katakana",
    "emoji",
    "ime_specific_marks",
    "non_ascii_symbols",
    "jis_kana_layout_dependent_keys",
    "named_text_or_send_string_actions",
)


def romaji_taps_for_text_action(action: str, output: str = "text") -> tuple[list[dict[str, Any]], list[str]]:
    if output != "text":
        return [], []
    if not action.startswith("U+"):
        return [], ["composition_mode_requires_unicode_action"]
    codepoint = action[2:].upper()
    keys = ROMAJI_US_IME_KEYCODES.get(codepoint)
    if not keys:
        return [], [COMPOSITION_BLOCKING_REASON_BY_CODEPOINT.get(codepoint, "romaji_sequence_not_defined")]
    return [{"type": "tap", "key": key} for key in keys], []
