#!/usr/bin/env python3
"""Static checks for 4.3 inch touch-panel flick input design documentation."""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOC = ROOT / "docs" / "input" / "touch-panel-flick-input-design.md"


def main() -> None:
    text = DOC.read_text(encoding="utf-8")

    required_phrases = [
        "osoyoo-4.3",
        "800x480",
        "12-key phone-style pad",
        "center / up / right / down / left",
        "PointerEvent",
        "Prerequisite",
        "UTF / Unicode / Send String",
        "unicode-send-string-safety-design.md",
        "pointercancel",
        "host IME / layout",
        "KC_KANA",
        "KC_LANG1",
        "logicd` へは",
        "最終 resolved action",
        "preview state",
        "default enabled にしません",
        "preview mode",
        "waveshare-8.8` は初期対象外",
        "DOM 静的テスト",
        "Windows 11 / Microsoft IME",
        "あいうえお、。ーがぱぁゃア日本語",
        "named `TEXT(kana_...)`",
        "改行 / Backspace / Enter は text code point ではなく key action",
        "Conversion Ownership",
        "keyboard-side GUI: flick gesture",
        "host IME: composition state",
        "candidate selection、辞書、学習",
        "一般的な日本語 IME engine の代替にはしない",
        "Host IME Controls",
        "`変換`",
        "`無変換`",
        "`確定`",
        "候補選択",
        "`KC_SPC`",
        "`KC_ENTER`",
        "`KC_ESC`",
        "`KC_UP`",
        "`KC_DOWN`",
        "US keyboard compatible keycodes",
        "`ime_controls` metadata",
        "IME control pad",
        "keycode output は",
        "`resolve_flick_pad_action` / `resolve_ime_control_action`",
        "final action only",
        "`resolveTouchFlickPreviewAction` / `resolveTouchFlickImePreviewAction`",
        "`POST /api/touch-panel/flick/resolve`",
        "`POST /api/touch-panel/flick/dispatch`",
        "`POST /api/interaction/text-send-safety/plan`",
        "action-level preflight",
        "`dispatch_policy`",
        "`host_ime_profile`",
        "`browser_may_call_dispatch=true`",
        "`browser_default_enabled=false`",
        "`browser_requires_local_enable=true`",
        "`送信: ON`",
        "`host-profile-required`",
        "`active_profile=None`",
        "`explicit_profile_required=true`",
        "Windows 11 / Microsoft IME profile",
        "`local U+XXXX` smoke",
        "`allowed_event.enabled=true`",
        "`dispatch=tap_action`",
        "`output=keycode`",
        "preflight 済みの `output=text`",
        "`explicit_host_profile`",
        "`host_ime_warning`",
        "`unicode_send_string_runner_cancel_path`",
        "`text_send_plan_preflight`",
        "`dispatch_event.enabled=false`",
        "preview state を logicd 送信用 payload に混ぜない",
        "`resolveTouchFlickDispatchEnvelope`",
        "`resolve_endpoint_unavailable`",
        "`daemon/logicd/touch_flick_dispatch.py`",
        "blocked preview-only",
        "`dispatch_touch_flick_event`",
        "explicit `tap_action`",
        "`output=text`",
        "`text_send.real_send_plan.v1`",
        "`TOUCH_FLICK` command",
        "resolver済み `event` object",
        "HTTP dispatch bridge",
        "final dispatch envelope",
        "fixed fullscreen panel",
        "6-column IME controls",
        "ellipsis / nowrap",
        "800x480 でボタン text がはみ出さない静的 CSS 制約",
        "Composition Plan Slice",
        "`POST /api/touch-panel/flick/composition-plan`",
        "`romaji_us_ime`",
        "`U+3042` maps to `KC_A`",
        "`U+304B` maps to `KC_K`, `KC_A`",
        "Dakuten, handakuten, small kana, comma, period, long vowel mark, full-width digits, and US shifted symbol aliases now use explicit romaji/keycode policy",
        "Katakana, emoji, IME-specific marks, non-ASCII symbols, JIS-kana layout dependent keys, and named text actions now have explicit `blocking_reasons` policy",
        "Remaining blocked text actions are classified as `composition_mode_requires_unicode_action`",
        "`GET /api/touch-panel/flick` exposes the same policy through `composition_mode.initial_scope`",
        "`blocked_policy_complete=true`",
        "`unclassified_blocked_reasons=[]`",
        "without mixing preview state into the `TOUCH_FLICK` dispatch envelope",
        "The browser flick preview now calls this route",
        "`romaji:<keys>`",
        "`composition:<blocking_reasons>`",
    ]
    for phrase in required_phrases:
        assert phrase in text, phrase
    print("ok: 4.3 inch touch-panel flick input design keeps IME/profile/event boundaries explicit")


if __name__ == "__main__":
    main()
