#!/usr/bin/env python3
"""Host-only regression tests for early USB gadget capture and adoption."""
from __future__ import annotations

import hashlib
import importlib.util
import json
import os
from pathlib import Path
import platform
import stat
import subprocess
import sys
import tempfile
from typing import Callable


ROOT = Path(__file__).resolve().parents[1]
TOOL = ROOT / "tools" / "rpi_os_early_gadget_adopt.py"

SPEC = importlib.util.spec_from_file_location("rpi_os_early_gadget_adopt", TOOL)
assert SPEC and SPEC.loader
ADOPT = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(ADOPT)

SOURCE = "4c4c830f53f0123456789abcdef0123456789abc"
KERNEL = "6.18.34+rpt-rpi-v8"
GADGET_NAME = "cqa02303v5"
UDC = "20980000.usb"
PACKAGE_VERSION = "0.0.2033+git4c4c830f53f0"
FIXTURE_HOSTNAME = "hidloom-fixture"

IDENTITY = {
    "HIDLOOM_USB_VENDOR_ID": "0x1d6b",
    "HIDLOOM_USB_PRODUCT_ID": "0x0105",
    "HIDLOOM_USB_MANUFACTURER": FIXTURE_HOSTNAME,
    "HIDLOOM_USB_PRODUCT_NAME": FIXTURE_HOSTNAME,
    "HIDLOOM_USB_SERIAL": "vial:f64c2b3c",
    "HIDLOOM_USB_SERIAL_SUFFIX": "",
    "HIDLOOM_USB_US_SUB_KEYBOARD": "1",
    "HIDLOOM_WINDOWS_IME_CUSTOM_HID": "0",
}

REPORTS = {
    "main": bytes.fromhex("05010906a1018501c0"),
    "raw": bytes.fromhex("0660ff0961a101c0"),
    "us_sub": bytes.fromhex("05010906a101c0"),
    "windows_ime_custom": bytes.fromhex(
        "0670ff0901a101150026ff007508950809028102950809039102c0"
    ),
}


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def write_bytes(path: Path, data: bytes, mode: int = 0o644) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)
    path.chmod(mode)


def write_text(path: Path, value: str, mode: int = 0o644) -> None:
    write_bytes(path, value.encode(), mode)


def write_json(path: Path, payload: object, mode: int = 0o644) -> bytes:
    data = (json.dumps(payload, indent=2, sort_keys=True) + "\n").encode()
    write_bytes(path, data, mode)
    return data


def identity_env_bytes(identity: dict[str, str] = IDENTITY) -> bytes:
    lines = ["# Generated by rpi_os_early_initramfs.py; do not edit."]
    for key in sorted(identity):
        lines.append(f"{key}='{identity[key]}'")
        lines.append(f"export {key}")
    return ("\n".join(lines) + "\n").encode()


def dpkg_architecture() -> str:
    machine = platform.machine().lower()
    if machine in {"x86_64", "amd64"}:
        return "amd64"
    if machine in {"aarch64", "arm64"}:
        return "arm64"
    return machine


class Fixture:
    def __init__(self, root: Path):
        self.root = root
        self.marker = root / "run/hidloom-early/gadget-bound.json"
        self.input_manifest = root / "accepted/input-e1.json"
        self.accepted = root / "accepted/early-image.json"
        self.runtime_contract = root / "run/hidloom-early/contract.json"
        self.configfs_root = root / "configfs/usb_gadget"
        self.proc_root = root / "proc"
        self.sys_root = root / "sys"
        self.dev_root = root / "dev"
        self.package_root = root / "package-root"
        self.profile_root = root / "profiles"
        self.runtime_profile_marker = root / "mnt/p3/device_profile.json"
        self.helper = root / "package-root/usr/lib/hidloom/bin/hidloom-usb-gadget-fast"
        self.gadget = self.configfs_root / GADGET_NAME
        self.owner_uid = os.getuid()
        self._build()

    def _build(self) -> None:
        write_text(self.proc_root / "sys/kernel/osrelease", KERNEL + "\n")
        write_text(self.proc_root / "sys/kernel/hostname", FIXTURE_HOSTNAME + "\n")
        (self.sys_root / "class/udc" / UDC).mkdir(parents=True)

        profile = {
            "schema": ADOPT.PROFILE_SCHEMA,
            "id": "keyboard-ver1",
            "label": "Keyboard ver1.0",
            "kind": "keyboard",
            "runtime_files": {},
            "config_files": {},
            "services": {},
        }
        profile_path = self.profile_root / "keyboard-ver1/profile.json"
        profile_bytes = write_json(profile_path, profile)
        profile_contract = {"id": "keyboard-ver1", "sha256": sha256(profile_bytes)}
        write_json(
            self.runtime_profile_marker,
            {
                "schema": ADOPT.PROFILE_SCHEMA,
                "id": "keyboard-ver1",
                "kind": "keyboard",
                "selected_by": "fixture",
            },
        )

        helper_bytes = b"fixture-static-helper\x00" + bytes(range(64))
        write_bytes(self.helper, helper_bytes, 0o755)
        helper_sha = sha256(helper_bytes)
        write_json(
            self.package_root / "var/lib/hidloom/package-manifest.json",
            {
                "schema": ADOPT.PACKAGE_MANIFEST_SCHEMA,
                "git_sha": SOURCE[:12],
                "package": "hidloom-fixture-aarch64",
            },
        )
        write_text(
            self.package_root / "var/lib/dpkg/status",
            (
                "Package: hidloom-core\n"
                "Status: install ok installed\n"
                f"Architecture: {dpkg_architecture()}\n"
                f"Version: {PACKAGE_VERSION}\n\n"
                "Package: hidloom-profile-keyboard-ver1\n"
                "Status: install ok installed\n"
                f"Architecture: {dpkg_architecture()}\n"
                f"Version: {PACKAGE_VERSION}\n"
            ),
        )

        self._build_gadget()
        ordered = ["hid.usb0", "hid.usb1", "hid.usb2"]
        volatile = ADOPT.volatile_configfs_entries(ordered)
        all_entries = ADOPT.snapshot_configfs_entries(self.gadget)
        static_entries = {
            path: entry for path, entry in all_entries.items() if path not in set(volatile)
        }
        gadget_contract = {
            "schema": ADOPT.GADGET_CONTRACT_SCHEMA,
            "name": GADGET_NAME,
            "udc": UDC,
            "config_name": "c.1",
            "ordered_functions": ordered,
            "volatile_entries": volatile,
            "dev_nodes": {
                "hid.usb0": "hidg0",
                "hid.usb1": "hidg1",
                "hid.usb2": "hidg2",
            },
            "entries": static_entries,
        }
        report_records = {
            name: {"size": len(data), "sha256": sha256(data)}
            for name, data in sorted(REPORTS.items())
        }
        descriptor_contract = {
            "contract_sha256": ADOPT.canonical_sha256(report_records),
            "reports": report_records,
        }
        packages = {
            "core": {"name": "hidloom-core", "version": PACKAGE_VERSION},
            "profile": {
                "name": "hidloom-profile-keyboard-ver1",
                "version": PACKAGE_VERSION,
            },
        }
        runtime_payload = {
            "schema": ADOPT.RUNTIME_CONTRACT_SCHEMA,
            "source": SOURCE,
            "kernel_release": KERNEL,
            "profile": profile_contract,
            "identity_sha256": sha256(identity_env_bytes()),
            "helper_sha256": helper_sha,
            "descriptor_contract_sha256": descriptor_contract["contract_sha256"],
            "module_sha256": {
                "libcomposite": "1" * 64,
                "usb_f_hid": "2" * 64,
            },
        }
        runtime_bytes = write_json(self.runtime_contract, runtime_payload, 0o600)
        runtime_sha = sha256(runtime_bytes)
        accepted_payload = {
            "schema": ADOPT.IMAGE_SCHEMA,
            "kernel_release": KERNEL,
            "source": SOURCE,
            "identity": IDENTITY,
            "profile": profile_contract,
            "descriptors": descriptor_contract,
            "helper": {
                "architecture": platform.machine().lower(),
                "static": True,
                "sha256": helper_sha,
            },
            "overlay": {
                "files": [
                    {
                        "path": "conf/hidloom-early-contract.json",
                        "size": len(runtime_bytes),
                        "sha256": runtime_sha,
                    },
                    {
                        "path": "conf/hidloom-early-usb.env",
                        "size": len(identity_env_bytes()),
                        "sha256": sha256(identity_env_bytes()),
                    },
                    {
                        "path": "usr/lib/hidloom/early/hidloom-usb-gadget-fast",
                        "size": len(helper_bytes),
                        "sha256": helper_sha,
                    },
                ]
            },
            "runtime_contract": {**runtime_payload, "sha256": runtime_sha},
        }
        write_json(self.input_manifest, accepted_payload, 0o600)
        accepted_payload["adopt"] = {
            "schema": ADOPT.ADOPT_CONTRACT_SCHEMA,
            "packages": packages,
            "gadget": gadget_contract,
        }
        write_json(self.accepted, accepted_payload, 0o600)
        marker_payload = {
            "schema": ADOPT.MARKER_SCHEMA,
            "state": "bound",
            "runtime_contract_sha256": runtime_sha,
            "kernel_release": KERNEL,
            "ready_uptime_seconds": 2.125,
        }
        write_json(self.marker, marker_payload, 0o600)

    def _build_gadget(self) -> None:
        for name, value in {
            "idVendor": "0x1d6b",
            "idProduct": "0x0105",
            "bcdDevice": "0x0100",
            "bcdUSB": "0x0200",
            "bDeviceClass": "0x00",
            "bDeviceSubClass": "0x00",
            "bDeviceProtocol": "0x00",
            "bMaxPacketSize0": "0x40",
            "max_speed": "high-speed",
            "UDC": UDC,
        }.items():
            write_text(self.gadget / name, value)
        for language in ("0x409", "0x411"):
            write_text(
                self.gadget / "strings" / language / "manufacturer",
                IDENTITY["HIDLOOM_USB_MANUFACTURER"],
            )
            write_text(
                self.gadget / "strings" / language / "product",
                IDENTITY["HIDLOOM_USB_PRODUCT_NAME"],
            )
            write_text(
                self.gadget / "strings" / language / "serialnumber",
                IDENTITY["HIDLOOM_USB_SERIAL"],
            )
        function_specs = {
            "hid.usb0": ("0", "0", "9", REPORTS["main"], "240:0", "hidg0"),
            "hid.usb1": ("0", "0", "32", REPORTS["raw"], "240:1", "hidg1"),
            "hid.usb2": ("1", "1", "8", REPORTS["us_sub"], "240:2", "hidg2"),
        }
        for function, (
            protocol,
            subclass,
            length,
            descriptor,
            device,
            node,
        ) in function_specs.items():
            directory = self.gadget / "functions" / function
            write_text(directory / "protocol", protocol)
            write_text(directory / "subclass", subclass)
            write_text(directory / "report_length", length)
            write_bytes(directory / "report_desc", descriptor)
            write_text(directory / "dev", device)
            write_text(self.dev_root / node, device)
        config = self.gadget / "configs/c.1"
        write_text(config / "MaxPower", "250")
        write_text(config / "bmAttributes", "0x80")
        for language in ("0x409", "0x411"):
            write_text(
                config / "strings" / language / "configuration",
                "Config 1: HID Keyboard+Mouse+Consumer+RawHID+UsSubKeyboard",
            )
        for function in function_specs:
            link = config / function
            link.symlink_to(self.gadget / "functions" / function)
        for name, value in {
            "b_vendor_code": "0x00",
            "qw_sign": "",
            "use": "0",
        }.items():
            write_text(self.gadget / "os_desc" / name, value)

    def command(self, accepted_manifest: Path | None = None) -> list[str]:
        return [
            sys.executable,
            str(TOOL),
            "verify",
            "--marker",
            str(self.marker),
            "--accepted-manifest",
            str(accepted_manifest or self.accepted),
            "--runtime-contract",
            str(self.runtime_contract),
            "--configfs-root",
            str(self.configfs_root),
            "--proc-root",
            str(self.proc_root),
            "--sys-root",
            str(self.sys_root),
            "--dev-root",
            str(self.dev_root),
            "--package-root",
            str(self.package_root),
            "--profile-root",
            str(self.profile_root),
            "--runtime-profile-marker",
            str(self.runtime_profile_marker),
            "--helper",
            str(self.helper),
            "--gadget-name",
            GADGET_NAME,
            "--expected-owner-uid",
            str(self.owner_uid),
            "--allow-regular-dev-fixtures",
        ]

    def capture_command(self, output: Path) -> list[str]:
        return [
            sys.executable,
            str(TOOL),
            "capture",
            "--manifest",
            str(self.input_manifest),
            "--output",
            str(output),
            "--core-package-name",
            "hidloom-core",
            "--profile-package-name",
            "hidloom-profile-keyboard-ver1",
            "--config-name",
            "c.1",
            "--configfs-root",
            str(self.configfs_root),
            "--proc-root",
            str(self.proc_root),
            "--sys-root",
            str(self.sys_root),
            "--dev-root",
            str(self.dev_root),
            "--package-root",
            str(self.package_root),
            "--profile-root",
            str(self.profile_root),
            "--runtime-profile-marker",
            str(self.runtime_profile_marker),
            "--helper",
            str(self.helper),
            "--gadget-name",
            GADGET_NAME,
            "--expected-owner-uid",
            str(self.owner_uid),
            "--allow-regular-dev-fixtures",
        ]

    def clear_marker_command(self) -> list[str]:
        return [
            sys.executable,
            str(TOOL),
            "clear-marker-after-unbind",
            "--marker",
            str(self.marker),
            "--runtime-contract",
            str(self.runtime_contract),
            "--configfs-root",
            str(self.configfs_root),
            "--gadget-name",
            GADGET_NAME,
            "--expected-owner-uid",
            str(self.owner_uid),
        ]

    def environment(self, **updates: str) -> dict[str, str]:
        result = {
            key: value
            for key, value in os.environ.items()
            if not key.startswith("HIDLOOM_USB_") and key != "HIDLOOM_WINDOWS_IME_CUSTOM_HID"
        }
        result.update(IDENTITY)
        result.update(updates)
        return result

    def run(
        self,
        accepted_manifest: Path | None = None,
        **env_updates: str,
    ) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            self.command(accepted_manifest),
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            env=self.environment(**env_updates),
            check=False,
        )

    def run_capture(
        self,
        output: Path,
        **env_updates: str,
    ) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            self.capture_command(output),
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            env=self.environment(**env_updates),
            check=False,
        )

    def run_clear_marker(self) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            self.clear_marker_command(),
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            env=self.environment(),
            check=False,
        )


def tree_fingerprint(root: Path) -> dict[str, tuple[object, ...]]:
    result: dict[str, tuple[object, ...]] = {}

    def walk(path: Path) -> None:
        for child in sorted(path.iterdir(), key=lambda item: item.name):
            details = child.lstat()
            relative = child.relative_to(root).as_posix()
            base = (
                stat.S_IFMT(details.st_mode),
                stat.S_IMODE(details.st_mode),
                details.st_uid,
                details.st_gid,
                details.st_size,
                details.st_mtime_ns,
                details.st_ctime_ns,
                details.st_ino,
            )
            if child.is_symlink():
                result[relative] = (*base, "symlink", os.readlink(child))
            elif child.is_dir():
                result[relative] = (*base, "directory")
                walk(child)
            else:
                result[relative] = (*base, "file", sha256(child.read_bytes()))
    walk(root)
    return result


def expect_unsafe(
    mutate: Callable[[Fixture], None],
    *,
    env_updates: dict[str, str] | None = None,
) -> None:
    with tempfile.TemporaryDirectory(prefix="hidloom-adopt-negative-") as directory:
        fixture = Fixture(Path(directory))
        mutate(fixture)
        result = fixture.run(**(env_updates or {}))
        assert result.returncode == ADOPT.EXIT_UNSAFE, (
            result.returncode,
            result.stdout,
            result.stderr,
        )
        assert result.stderr.startswith("unsafe:")


def expect_capture_unsafe(
    mutate: Callable[[Fixture], None],
    *,
    env_updates: dict[str, str] | None = None,
) -> None:
    with tempfile.TemporaryDirectory(prefix="hidloom-capture-negative-") as directory:
        base = Path(directory)
        fixture = Fixture(base / "fixture")
        output_directory = base / "captures"
        output_directory.mkdir()
        output = output_directory / "accepted.json"
        mutate(fixture)
        before = tree_fingerprint(fixture.root)
        result = fixture.run_capture(output, **(env_updates or {}))
        after = tree_fingerprint(fixture.root)
        assert result.returncode == ADOPT.EXIT_UNSAFE, (
            result.returncode,
            result.stdout,
            result.stderr,
        )
        assert result.stderr.startswith("unsafe:")
        assert not output.exists(), "failed capture left an output file"
        assert before == after, "failed capture changed fixture bytes or metadata"


def main() -> None:
    with tempfile.TemporaryDirectory(prefix="hidloom-capture-match-") as directory:
        base = Path(directory)
        fixture = Fixture(base / "fixture")
        output_directory = base / "captures"
        output_directory.mkdir()
        first = output_directory / "accepted-first.json"
        second = output_directory / "accepted-second.json"
        before = tree_fingerprint(fixture.root)

        first_result = fixture.run_capture(first)
        assert first_result.returncode == ADOPT.EXIT_ADOPTED, first_result.stderr
        first_payload = json.loads(first_result.stdout)
        assert first_payload["status"] == "captured"
        assert first_payload["configfs_mutations"] == 0
        assert first_payload["gadget"] == GADGET_NAME
        assert first_payload["udc"] == UDC
        assert first_payload["sha256"] == sha256(first.read_bytes())
        assert stat.S_IMODE(first.stat().st_mode) == 0o600

        second_result = fixture.run_capture(second)
        assert second_result.returncode == ADOPT.EXIT_ADOPTED, second_result.stderr
        assert first.read_bytes() == second.read_bytes(), "captures are not deterministic"
        assert first.read_bytes() == fixture.accepted.read_bytes()
        assert stat.S_IMODE(second.stat().st_mode) == 0o600

        root_package_args = ADOPT.parse_args(
            fixture.capture_command(output_directory / "root-package-path.json")[2:]
        )
        root_package_args.package_root = Path("/")
        assert ADOPT.capture_output_path(root_package_args) == (
            output_directory / "root-package-path.json"
        ).resolve()

        verify_result = fixture.run(first)
        assert verify_result.returncode == ADOPT.EXIT_ADOPTED, verify_result.stderr
        assert json.loads(verify_result.stdout)["status"] == "adopted"

        original_output = tree_fingerprint(output_directory)
        existing_result = fixture.run_capture(first)
        assert existing_result.returncode == ADOPT.EXIT_UNSAFE
        assert existing_result.stderr.startswith("unsafe:")
        assert tree_fingerprint(output_directory) == original_output

        after = tree_fingerprint(fixture.root)
        assert before == after, "capture or captured verification changed input metadata"

    with tempfile.TemporaryDirectory(prefix="hidloom-ep0-normalization-") as directory:
        base = Path(directory)
        fixture = Fixture(base / "fixture")
        output_directory = base / "captures"
        output_directory.mkdir()
        output = output_directory / "accepted.json"

        write_text(fixture.gadget / "bMaxPacketSize0", "0x00")
        capture_result = fixture.run_capture(output)
        assert capture_result.returncode == ADOPT.EXIT_ADOPTED, capture_result.stderr
        captured_gadget = json.loads(output.read_text(encoding="utf-8"))["adopt"]["gadget"]
        assert captured_gadget["schema"] == "hidloom.configfs-usb-gadget.snapshot.v2"
        assert "bMaxPacketSize0" in captured_gadget["volatile_entries"]
        assert "bMaxPacketSize0" not in captured_gadget["entries"]

        write_text(fixture.gadget / "bMaxPacketSize0", "0x40")
        verify_result = fixture.run(output)
        assert verify_result.returncode == ADOPT.EXIT_ADOPTED, verify_result.stderr
        assert json.loads(verify_result.stdout)["status"] == "adopted"

    with tempfile.TemporaryDirectory(prefix="hidloom-ep0-in-verify-") as directory:
        base = Path(directory)

        normalizing = Fixture(base / "normalizing")
        write_text(normalizing.gadget / "bMaxPacketSize0", "0x00")
        calls, error = _direct_verify_with_ep0_change(normalizing, "0x40")
        assert calls == 2
        assert error is None, error

        disappearing = Fixture(base / "disappearing")
        write_text(disappearing.gadget / "bMaxPacketSize0", "0x00")
        calls, error = _direct_verify_with_ep0_change(disappearing, None)
        assert calls == 1
        assert error is not None and "cannot inspect configfs bMaxPacketSize0" in error

        becoming_invalid = Fixture(base / "becoming-invalid")
        write_text(becoming_invalid.gadget / "bMaxPacketSize0", "0x00")
        calls, error = _direct_verify_with_ep0_change(becoming_invalid, "0x07")
        assert calls == 1
        assert error is not None and "bMaxPacketSize0 is invalid" in error

        static_changing = Fixture(base / "static-changing")
        write_text(static_changing.gadget / "bMaxPacketSize0", "0x00")
        calls, error = _direct_verify_with_ep0_change(
            static_changing,
            "0x40",
            change_static_entry=True,
        )
        assert calls == 2
        assert error == "configfs changed while it was being verified"

    with tempfile.TemporaryDirectory(prefix="hidloom-capture-windows-ime-") as directory:
        base = Path(directory)
        fixture = Fixture(base / "fixture")
        output_directory = base / "captures"
        output_directory.mkdir()
        output = output_directory / "accepted.json"
        _enable_windows_ime(fixture)
        result = fixture.run_capture(
            output,
            HIDLOOM_WINDOWS_IME_CUSTOM_HID="1",
        )
        assert result.returncode == ADOPT.EXIT_ADOPTED, result.stderr
        captured = json.loads(output.read_text(encoding="utf-8"))
        gadget = captured["adopt"]["gadget"]
        assert gadget["ordered_functions"] == [
            "hid.usb0",
            "hid.usb1",
            "hid.usb2",
            "hid.usb4",
        ]
        assert gadget["dev_nodes"]["hid.usb4"] == "hidg4"

    with tempfile.TemporaryDirectory(prefix="hidloom-adopt-match-") as directory:
        fixture = Fixture(Path(directory))
        before = tree_fingerprint(fixture.root)
        result = fixture.run()
        after = tree_fingerprint(fixture.root)
        assert result.returncode == ADOPT.EXIT_ADOPTED, result.stderr
        payload = json.loads(result.stdout)
        assert payload["status"] == "adopted"
        assert payload["configfs_mutations"] == 0
        assert payload["gadget"] == GADGET_NAME
        assert payload["udc"] == UDC
        assert before == after, "successful verification changed fixture bytes or metadata"

    with tempfile.TemporaryDirectory(prefix="hidloom-adopt-unbound-") as directory:
        fixture = Fixture(Path(directory))
        fixture.marker.unlink()
        write_text(fixture.gadget / "UDC", "")
        before = tree_fingerprint(fixture.root)
        result = fixture.run()
        after = tree_fingerprint(fixture.root)
        assert result.returncode == ADOPT.EXIT_CREATE_SENTINEL, result.stderr
        payload = json.loads(result.stdout)
        assert payload["status"] == "create-required"
        assert "stably unbound" in payload["reason"]
        assert before == after, "unbound sentinel check changed fixture metadata"

    with tempfile.TemporaryDirectory(prefix="hidloom-adopt-restart-") as directory:
        fixture = Fixture(Path(directory))
        marker_bytes = fixture.marker.read_bytes()
        bound_result = fixture.run_clear_marker()
        assert bound_result.returncode == ADOPT.EXIT_UNSAFE
        assert fixture.marker.read_bytes() == marker_bytes

        write_text(fixture.gadget / "UDC", "")
        before = tree_fingerprint(fixture.root)
        clear_result = fixture.run_clear_marker()
        assert clear_result.returncode == ADOPT.EXIT_ADOPTED, clear_result.stderr
        clear_payload = json.loads(clear_result.stdout)
        assert clear_payload["status"] == "marker-cleared"
        assert clear_payload["marker_mutations"] == 1
        assert clear_payload["configfs_mutations"] == 0
        assert not fixture.marker.exists()
        after = tree_fingerprint(fixture.root)
        for fingerprint in (before, after):
            fingerprint.pop("run/hidloom-early", None)
            fingerprint.pop("run/hidloom-early/gadget-bound.json", None)
        assert before == after, "marker cleanup changed state outside its marker"

        recreate_result = fixture.run()
        assert recreate_result.returncode == ADOPT.EXIT_CREATE_SENTINEL
        assert json.loads(recreate_result.stdout)["status"] == "create-required"

    with tempfile.TemporaryDirectory(prefix="hidloom-adopt-stop-malformed-") as directory:
        fixture = Fixture(Path(directory))
        write_text(fixture.gadget / "UDC", "")
        fixture.marker.write_text("{}\n", encoding="utf-8")
        malformed_bytes = fixture.marker.read_bytes()
        result = fixture.run_clear_marker()
        assert result.returncode == ADOPT.EXIT_UNSAFE
        assert fixture.marker.read_bytes() == malformed_bytes

    with tempfile.TemporaryDirectory(prefix="hidloom-adopt-sentinel-") as directory:
        root = Path(directory)
        command = [
            sys.executable,
            str(TOOL),
            "--marker", str(root / "marker.json"),
            "--accepted-manifest", str(root / "accepted.json"),
            "--runtime-contract", str(root / "contract.json"),
            "--configfs-root", str(root / "configfs"),
            "--proc-root", str(root / "proc"),
            "--sys-root", str(root / "sys"),
            "--dev-root", str(root / "dev"),
            "--package-root", str(root / "package"),
            "--profile-root", str(root / "profiles"),
            "--runtime-profile-marker", str(root / "profile.json"),
            "--helper", str(root / "helper"),
            "--gadget-name", GADGET_NAME,
            "--expected-owner-uid", str(os.getuid()),
        ]
        result = subprocess.run(command, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        assert result.returncode == ADOPT.EXIT_CREATE_SENTINEL, result.stderr
        assert json.loads(result.stdout)["status"] == "create-required"

    missing_capture_arguments = subprocess.run(
        [sys.executable, str(TOOL), "capture"],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    assert missing_capture_arguments.returncode == ADOPT.EXIT_UNSAFE
    assert missing_capture_arguments.stderr.startswith("unsafe: command line:")

    expect_unsafe(lambda fixture: fixture.marker.write_text("{", encoding="utf-8"))
    expect_unsafe(
        lambda fixture: _mutate_json(
            fixture.marker, lambda payload: payload.__setitem__("schema", "wrong")
        )
    )
    expect_unsafe(
        lambda fixture: _mutate_json(
            fixture.accepted,
            lambda payload: payload["adopt"].__setitem__("schema", "wrong"),
        )
    )
    expect_unsafe(
        lambda fixture: _mutate_json(
            fixture.accepted,
            lambda payload: payload["adopt"]["gadget"].__setitem__(
                "schema", "hidloom.configfs-usb-gadget.snapshot.v1"
            ),
        )
    )
    expect_unsafe(
        lambda fixture: fixture.runtime_contract.write_bytes(
            fixture.runtime_contract.read_bytes() + b" "
        )
    )
    expect_unsafe(
        lambda fixture: write_text(
            fixture.proc_root / "sys/kernel/osrelease", "wrong\n"
        )
    )
    expect_unsafe(
        lambda fixture: _mutate_json(
            fixture.accepted,
            lambda payload: payload["helper"].__setitem__("architecture", "wrong-arch"),
        )
    )
    expect_unsafe(
        lambda fixture: write_text(
            fixture.package_root / "var/lib/dpkg/status",
            (fixture.package_root / "var/lib/dpkg/status")
            .read_text(encoding="utf-8")
            .replace(PACKAGE_VERSION, PACKAGE_VERSION + ".wrong", 1),
        )
    )
    expect_unsafe(
        lambda fixture: fixture.profile_root.joinpath("keyboard-ver1/profile.json").write_bytes(
            fixture.profile_root.joinpath("keyboard-ver1/profile.json").read_bytes() + b" "
        )
    )
    expect_unsafe(lambda fixture: fixture.helper.write_bytes(fixture.helper.read_bytes() + b"x"))
    expect_unsafe(lambda fixture: None, env_updates={"HIDLOOM_USB_PRODUCT_ID": "0x9999"})
    expect_unsafe(
        lambda fixture: fixture.gadget.joinpath(
            "functions/hid.usb0/report_desc"
        ).write_bytes(b"bad")
    )
    expect_unsafe(lambda fixture: fixture.gadget.joinpath("functions/hid.usb9").mkdir())
    expect_unsafe(lambda fixture: write_text(fixture.gadget / "bcdUSB", "0x0300"))
    expect_unsafe(lambda fixture: fixture.gadget.joinpath("bMaxPacketSize0").unlink())
    expect_unsafe(
        lambda fixture: write_text(fixture.gadget / "bMaxPacketSize0", "0x07")
    )
    expect_unsafe(_replace_ep0_with_symlink)
    expect_unsafe(_retarget_main_symlink)
    expect_unsafe(lambda fixture: write_text(fixture.gadget / "UDC", "wrong-udc"))
    expect_unsafe(lambda fixture: write_text(fixture.dev_root / "hidg2", "240:9"))
    expect_unsafe(lambda fixture: fixture.accepted.unlink())
    expect_unsafe(lambda fixture: fixture.marker.unlink())
    expect_unsafe(_make_markerless_udc_symlink)

    expect_capture_unsafe(
        lambda fixture: write_text(fixture.proc_root / "sys/kernel/osrelease", "wrong\n")
    )
    expect_capture_unsafe(
        lambda fixture: write_text(
            fixture.package_root / "var/lib/dpkg/status",
            (fixture.package_root / "var/lib/dpkg/status")
            .read_text(encoding="utf-8")
            .replace(f"Architecture: {dpkg_architecture()}", "Architecture: wrong", 1),
        )
    )
    expect_capture_unsafe(
        lambda fixture: _mutate_json(
            fixture.package_root / "var/lib/hidloom/package-manifest.json",
            lambda payload: payload.__setitem__("git_sha", "f" * 40),
        )
    )
    expect_capture_unsafe(
        lambda fixture: fixture.profile_root.joinpath(
            "keyboard-ver1/profile.json"
        ).write_bytes(
            fixture.profile_root.joinpath("keyboard-ver1/profile.json").read_bytes()
            + b" "
        )
    )
    expect_capture_unsafe(
        lambda fixture: fixture.helper.write_bytes(fixture.helper.read_bytes() + b"x")
    )
    expect_capture_unsafe(
        lambda fixture: None,
        env_updates={"HIDLOOM_USB_PRODUCT_ID": "0x9999"},
    )
    expect_capture_unsafe(
        lambda fixture: fixture.gadget.joinpath(
            "functions/hid.usb0/report_desc"
        ).write_bytes(b"bad")
    )
    expect_capture_unsafe(
        lambda fixture: fixture.gadget.joinpath("bMaxPacketSize0").unlink()
    )
    expect_capture_unsafe(
        lambda fixture: write_text(fixture.gadget / "bMaxPacketSize0", "invalid")
    )
    expect_capture_unsafe(
        lambda fixture: _mutate_json(
            fixture.input_manifest,
            lambda payload: payload.__setitem__("adopt", {}),
        )
    )
    expect_capture_unsafe(_forge_e1_identity_hash)
    expect_capture_unsafe(
        lambda fixture: _enable_windows_ime(fixture, descriptor=b"bad"),
        env_updates={"HIDLOOM_WINDOWS_IME_CUSTOM_HID": "1"},
    )

    with tempfile.TemporaryDirectory(prefix="hidloom-capture-existing-") as directory:
        base = Path(directory)
        fixture = Fixture(base / "fixture")
        output_directory = base / "captures"
        output_directory.mkdir()
        output = output_directory / "accepted.json"
        write_bytes(output, b"do-not-overwrite", 0o640)
        before = tree_fingerprint(base)
        result = fixture.run_capture(output)
        after = tree_fingerprint(base)
        assert result.returncode == ADOPT.EXIT_UNSAFE
        assert result.stderr.startswith("unsafe:")
        assert before == after, "existing output was changed"

    print("ok: Raspberry Pi OS early gadget capture and adopt verifier")


def _mutate_json(path: Path, mutate: Callable[[dict[str, object]], None]) -> None:
    payload = json.loads(path.read_text(encoding="utf-8"))
    mutate(payload)
    write_json(path, payload, stat.S_IMODE(path.stat().st_mode))


def _retarget_main_symlink(fixture: Fixture) -> None:
    link = fixture.gadget / "configs/c.1/hid.usb0"
    link.unlink()
    link.symlink_to(fixture.gadget / "functions/hid.usb1")


def _make_markerless_udc_symlink(fixture: Fixture) -> None:
    fixture.marker.unlink()
    udc = fixture.gadget / "UDC"
    udc.unlink()
    udc.symlink_to(fixture.proc_root / "sys/kernel/hostname")


def _replace_ep0_with_symlink(fixture: Fixture) -> None:
    ep0 = fixture.gadget / "bMaxPacketSize0"
    ep0.unlink()
    ep0.symlink_to(fixture.gadget / "bcdUSB")


def _direct_verify_with_ep0_change(
    fixture: Fixture,
    next_value: str | None,
    *,
    change_static_entry: bool = False,
) -> tuple[int, str | None]:
    """Change EP0 after its first validated snapshot inside one verification."""
    accepted = json.loads(fixture.accepted.read_text(encoding="utf-8"))
    gadget_contract = accepted["adopt"]["gadget"]
    original_validate = ADOPT.validate_ep0_max_packet_size
    calls = 0

    def validate_then_change(gadget: Path) -> int:
        nonlocal calls
        value = original_validate(gadget)
        calls += 1
        if calls == 1:
            path = gadget / "bMaxPacketSize0"
            if next_value is None:
                path.unlink()
            else:
                write_text(path, next_value)
            if change_static_entry:
                write_text(gadget / "bcdUSB", "0x0300")
        return value

    ADOPT.validate_ep0_max_packet_size = validate_then_change
    error: str | None = None
    try:
        ADOPT.validate_gadget_contract(
            fixture.configfs_root,
            fixture.sys_root,
            fixture.dev_root,
            gadget_contract,
            IDENTITY,
            allow_regular_dev_fixtures=True,
        )
    except ADOPT.AdoptError as exc:
        error = str(exc)
    finally:
        ADOPT.validate_ep0_max_packet_size = original_validate
    return calls, error


def _rewrite_e1_runtime_contract(
    fixture: Fixture,
    payload: dict[str, object],
) -> None:
    runtime = payload["runtime_contract"]
    assert isinstance(runtime, dict)
    content = {key: value for key, value in runtime.items() if key != "sha256"}
    runtime_bytes = (json.dumps(content, indent=2, sort_keys=True) + "\n").encode()
    runtime_sha = sha256(runtime_bytes)
    runtime["sha256"] = runtime_sha
    overlay = payload["overlay"]
    assert isinstance(overlay, dict)
    files = overlay["files"]
    assert isinstance(files, list)
    contract_item = next(
        item
        for item in files
        if isinstance(item, dict)
        and item.get("path") == "conf/hidloom-early-contract.json"
    )
    contract_item["size"] = len(runtime_bytes)
    contract_item["sha256"] = runtime_sha
    write_json(fixture.input_manifest, payload, 0o600)


def _forge_e1_identity_hash(fixture: Fixture) -> None:
    payload = json.loads(fixture.input_manifest.read_text(encoding="utf-8"))
    forged_sha = "f" * 64
    runtime = payload["runtime_contract"]
    assert isinstance(runtime, dict)
    runtime["identity_sha256"] = forged_sha
    overlay = payload["overlay"]
    assert isinstance(overlay, dict)
    files = overlay["files"]
    assert isinstance(files, list)
    identity_item = next(
        item
        for item in files
        if isinstance(item, dict)
        and item.get("path") == "conf/hidloom-early-usb.env"
    )
    identity_item["sha256"] = forged_sha
    _rewrite_e1_runtime_contract(fixture, payload)


def _enable_windows_ime(
    fixture: Fixture,
    *,
    descriptor: bytes = REPORTS["windows_ime_custom"],
) -> None:
    payload = json.loads(fixture.input_manifest.read_text(encoding="utf-8"))
    identity = payload["identity"]
    assert isinstance(identity, dict)
    identity["HIDLOOM_WINDOWS_IME_CUSTOM_HID"] = "1"
    identity_bytes = identity_env_bytes(identity)
    runtime = payload["runtime_contract"]
    assert isinstance(runtime, dict)
    runtime["identity_sha256"] = sha256(identity_bytes)
    overlay = payload["overlay"]
    assert isinstance(overlay, dict)
    files = overlay["files"]
    assert isinstance(files, list)
    identity_item = next(
        item
        for item in files
        if isinstance(item, dict)
        and item.get("path") == "conf/hidloom-early-usb.env"
    )
    identity_item["size"] = len(identity_bytes)
    identity_item["sha256"] = sha256(identity_bytes)
    _rewrite_e1_runtime_contract(fixture, payload)

    function = fixture.gadget / "functions/hid.usb4"
    write_text(function / "protocol", "0")
    write_text(function / "subclass", "0")
    write_text(function / "report_length", "8")
    write_bytes(function / "report_desc", descriptor)
    write_text(function / "dev", "240:4")
    write_text(fixture.dev_root / "hidg4", "240:4")
    (fixture.gadget / "configs/c.1/hid.usb4").symlink_to(function)


if __name__ == "__main__":
    main()
