#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path
import shutil
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[1]


def run(root: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["python3", str(ROOT / "tools/public_asset_inventory.py"), str(root), "--check-only"],
        cwd=ROOT,
        capture_output=True,
        text=True,
    )


def main() -> None:
    checked = run(ROOT)
    assert checked.returncode == 0, checked.stdout + checked.stderr
    payload = json.loads(checked.stdout)
    assert payload["schema"] == "hidloom.public-asset-provenance.v1"
    assert payload["ready"] is True
    assert payload["summary"] == {
        "records": 5,
        "assets": 25,
        "declared": 25,
        "missing_declarations": 0,
        "stale_declarations": 0,
        "invalid_records": 0,
    }
    icons = next(item for item in payload["records"] if item["id"] == "hidloom-web-icons")
    assert icons["evidence"]["generator"] == "tools/generate_hidloom_icons.py"
    kicad = next(item for item in payload["records"] if item["id"] == "keyboard-kicad-designs")
    assert "KiCad Libraries License Exception" in kicad["upstream_material"]["license"]

    with tempfile.TemporaryDirectory() as tmp:
        fixture = Path(tmp)
        manifest = json.loads((ROOT / "config/public-assets.json").read_text(encoding="utf-8"))
        for relative in ["LICENSE", "config/public-assets.json"]:
            destination = fixture / relative
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(ROOT / relative, destination)
        for record in manifest["records"]:
            for relative in record["paths"]:
                destination = fixture / relative
                destination.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(ROOT / relative, destination)
        for relative in ("tools/generate_hidloom_icons.py", "script/test_hidloom_icon_assets.py"):
            destination = fixture / relative
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(ROOT / relative, destination)
        assert run(fixture).returncode == 0
        cache = fixture / "__pycache__/generated.pyc"
        cache.parent.mkdir()
        cache.write_bytes(b"generated bytecode fixture")
        export_manifest = fixture / "config/public-export.json"
        shutil.copy2(ROOT / "config/public-export.json", export_manifest)
        assert run(fixture).returncode == 0
        (fixture / "unreviewed-photo.jpg").write_bytes(b"\xff\xd8unreviewed fixture")
        blocked = run(fixture)
        assert blocked.returncode == 2
        blocked_payload = json.loads(blocked.stdout)
        assert blocked_payload["missing_declarations"] == ["unreviewed-photo.jpg"]

    print("ok: public assets have complete, exact provenance coverage")


if __name__ == "__main__":
    main()
