.TH BTD 8 "@HIDLOOM_VERSION@" "HIDloom" "System Administration"
.SH NAME
btd \- Bluetooth HID daemon
.SH SYNOPSIS
.B python3 -m btd.btd
.SH DESCRIPTION
.B btd
provides Bluetooth HID integration and host pairing/control behavior for the
keyboard runtime.
.SH OPTIONS
.TP
.B -h, --help
Show command help.
.SH SEE ALSO
.BR logicd (8),
.BR hidloom-ctrl (1)
.br
Bluetooth documentation:
https://github.com/cqa02303/hidloom/tree/@HIDLOOM_GIT_SHA@/docs/bluetooth
